"""add articles

Revision ID: f235b39675d0
Revises: t6u7v8w9x0y1
Create Date: 2026-08-06 10:52:04.587839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f235b39675d0'
down_revision: Union[str, None] = 't6u7v8w9x0y1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PUBLIC', 'AUTHENTICATED', 'RESTRICTED', name='articlelocktype').create(op.get_bind())
    op.create_table('article',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('thumbnail_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('lock_type', postgresql.ENUM('PUBLIC', 'AUTHENTICATED', 'RESTRICTED', name='articlelocktype', create_type=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('article_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creation_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('update_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('last_modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_modified_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_article_uuid'), 'article', ['article_uuid'], unique=False)
    op.create_index(op.f('ix_article_org_id'), 'article', ['org_id'], unique=False)
    op.create_index('ix_article_org_published_created', 'article', ['org_id', 'published', 'creation_date'], unique=False)
    op.create_index('ix_article_org_slug', 'article', ['org_id', 'slug'], unique=True)
    op.create_table('articleversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # Blocks become parent-polymorphic. Existing rows all belong to activities,
    # so relaxing NOT NULL is backward compatible and needs no backfill.
    op.alter_column('block', 'course_id', existing_type=sa.Integer(), nullable=True)
    op.alter_column('block', 'activity_id', existing_type=sa.Integer(), nullable=True)
    op.add_column('block', sa.Column('article_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_block_article_id', 'block', 'article', ['article_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM block WHERE article_id IS NOT NULL")
    op.drop_constraint('fk_block_article_id', 'block', type_='foreignkey')
    op.drop_column('block', 'article_id')
    op.alter_column('block', 'activity_id', existing_type=sa.Integer(), nullable=False)
    op.alter_column('block', 'course_id', existing_type=sa.Integer(), nullable=False)
    op.drop_table('articleversion')
    op.drop_index('ix_article_org_slug', table_name='article')
    op.drop_index('ix_article_org_published_created', table_name='article')
    op.drop_index(op.f('ix_article_org_id'), table_name='article')
    op.drop_index(op.f('ix_article_article_uuid'), table_name='article')
    op.drop_table('article')
    sa.Enum('PUBLIC', 'AUTHENTICATED', 'RESTRICTED', name='articlelocktype').drop(op.get_bind())
    # ### end Alembic commands ###
